#!/usr/bin/env ruby

require 'rasem'
require 'pry'

TABLET = {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5,
  f: 6,
  g: 7,
  h: 8,
  i: 9,
  j: 10,
  k: 11,
  l: 12,
  m: 13,
  n: 14,
  o: 15,
  p: 16,
  q: 18,
  r: 19,
  s: 100,
  t: 200,
  u: 300,
  v: 400,
  w: 500,
  x: 600,
  y: 700,
  z: 800,
  " ": 900
}

message = "Salut, les amis!"

def cister(message)
  message.downcase
  .gsub(/\W/, '')
  .squeeze
  .chars
  .map do |c|
    n = TABLET[c.to_sym] * 10
    r = rand(n)
    [n - r, r].shuffle
  end.flatten
end

# Extract units, tens, thousands, hundreds
def digits(num)
  cs = num.to_s.chars
  [].tap do |o|
    while cs.size > 0 do
      c = cs.shift
      o << (c + Array.new(cs.length) {|i| 0 }.join ).to_i
    end
  end
end

def snail(array)
  array.empty? ? [] : array.shift + snail(array.transpose.reverse)
end

sequence = cister(message)
sequence.map!{|n| digits(n) }

img = Rasem::SVGImage.new(:width=>100, :height=>100) do
  # Line that always appear
  line 50, 0, 50, 100
  # Lines that may or may not appear depending of the digit
  # Units
  line 50, 0, 100, 0
  line 50, 50, 100, 0
  line 50, 50, 100, 50
  line 50, 0, 100, 50
  # Tens
  # Hundreds
  # Thousands
end

File.open("tmp/test.svg", "w") do |f|
  img.write(f)
end

puts sequence.join '|'
