#!/usr/bin/env ruby

require 'rasem'
require 'pry'

TABLET = {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5,
  f: 6,
  g: 7,
  h: 8,
  i: 9,
  j: 10,
  k: 11,
  l: 12,
  m: 13,
  n: 14,
  o: 15,
  p: 16,
  q: 18,
  r: 19,
  s: 100,
  t: 200,
  u: 300,
  v: 400,
  w: 500,
  x: 600,
  y: 700,
  z: 800,
  " ": 900
}

message = "Salut, les amis!"

def cister(message)
  message.downcase
  .gsub(/\W/, '')
  .squeeze
  .chars
  .map do |c|
    n = TABLET[c.to_sym] * 10
    r = rand(n)
    [n - r, r].shuffle
  end.flatten
end

# Extract units, tens, thousands, hundreds
def digits(num)
  cs = num.to_s.chars
  [].tap do |o|
    while cs.size > 0 do
      c = cs.shift
      o << (c + Array.new(cs.length) {|i| 0 }.join ).to_i
    end
  end
end

def snail(array)
  array.empty? ? [] : array.shift + snail(array.transpose.reverse)
end

def symbol(num)
  img = Rasem::SVGImage.new(width: 100, height: 100) do
    # Line that always appear
    line 50, 0, 50, 100
    # Lines that may or may not appear depending of the digit
    case num
      when 1
        line 50, 0, 100, 0 # 1579 -
      when 2
        line 50, 50, 100, 50 # 289 _
      when 3
        line 50, 0, 100, 50 # 3 \
      when 4
        line 50, 50, 100, 0 # 45 /
      when 5
        line 50, 0, 100, 0 # 1579 -
        line 50, 50, 100, 0 # 45 /
      when 6
        line 100, 0, 100, 50 # 6789 |
      when 7
        line 50, 0, 100, 0 # 1579 -
        line 100, 0, 100, 50 # 6789 |
      when 8
        line 100, 0, 100, 50 # 6789 |
        line 50, 50, 100, 50 # 289 _
      when 9
        line 50, 0, 100, 0 # 1579 -
        line 100, 0, 100, 50 # 6789 |
        line 50, 50, 100, 50 # 289 _
      when 10
      when 20
      when 30
      when 40
      when 50
      when 60
      when 70
      when 80
      when 90
      when 100
      when 200
      when 300
      when 400
      when 500
      when 600
      when 700
      when 800
      when 900
      when 1000
      when 2000
      when 3000
      when 4000
      when 5000
      when 6000
      when 7000
      when 8000
      when 9000
    end
    # Units
    # line 50, 0, 100, 0 # 1579 -
    # line 50, 50, 100, 0 # 45 /
    # line 100, 0, 100, 50 # 6789 |
    # line 50, 0, 100, 50 # 3 \
    # line 50, 50, 100, 50 # 289 _
    # # Tens
    # line 50, 0, 0, 0 # 1579 -
    # line 0, 50, 0, 0 # 6789 |
    # line 50, 50, 0, 50 # 289 _
    # line 50, 50, 0, 0 # 45 \
    # # Hundreds
    # line 50, 50, 100, 50
    # line 100, 50, 100, 100
    # line 50, 100, 100, 100
    # line 50, 50, 100, 100
    # # Thousands
    # line 50, 50, 0, 50
    # line 50, 50, 0, 100
    # line 0, 50, 0, 100
    # line 50, 100, 0, 100
  end

  File.open("tmp/test.svg", "w") do |f|
    img.write(f)
  end
end

sequence = cister(message)
sequence.map!{|n| digits(n) }
puts sequence.join '|'
symbol(8)
